import type { Product } from '../types/product';

const baseImageUrl = 'https://via.placeholder.com/300';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'PlayStation 5',
    category: 'Consoles',
    price: 4499.99,
    originalPrice: 4999.99,
    image: `${baseImageUrl}?text=PlayStation+5`,
    rating: 4.8,
    description: 'O mais recente console da Sony com tecnologia de ponta para jogos em 4K.',
    inStock: true,
    brand: 'Sony',
    features: ['4K UHD', 'SSD de 1TB', 'Compatível com Ray Tracing'],
    specifications: {
      'Armazenamento': '1TB SSD',
      'Resolução Máxima': '8K',
      'Tipo de Mídia': 'Blu-ray 4K UHD',
    },
  },
  {
    id: '2',
    name: 'Xbox Series X',
    category: 'Consoles',
    price: 4299.99,
    originalPrice: 4799.99,
    image: `${baseImageUrl}?text=Xbox+Series+X`,
    rating: 4.7,
    description: 'O console mais poderoso da Microsoft com suporte a jogos em 4K a 120 FPS.',
    inStock: true,
    brand: 'Microsoft',
    features: ['4K UHD', '120 FPS', 'Ray Tracing', 'Retrocompatibilidade'],
    specifications: {
      'Armazenamento': '1TB SSD',
      'Resolução Máxima': '8K',
      'Tipo de Mídia': 'Blu-ray 4K UHD',
    },
  },
  {
    id: '3',
    name: 'Nintendo Switch',
    category: 'Consoles',
    price: 2499.99,
    originalPrice: 2799.99,
    image: `${baseImageUrl}?text=Nintendo+Switch`,
    rating: 4.6,
    description: 'Console híbrido que pode ser jogado em casa ou em movimento.',
    inStock: true,
    brand: 'Nintendo',
    features: ['Híbrido', 'Tela tátil', 'Joy-Cons removíveis'],
    specifications: {
      'Armazenamento': '32GB',
      'Resolução Máxima': '1080p (dock)',
      'Tipo de Mídia': 'Cartucho',
    },
  },
  {
    id: '4',
    name: 'RTX 4090',
    category: 'Placas de Vídeo',
    price: 12999.99,
    originalPrice: 13999.99,
    image: `${baseImageUrl}?text=RTX+4090`,
    rating: 4.9,
    description: 'A placa de vídeo mais avançada para jogos em 8K e criação de conteúdo.',
    inStock: true,
    brand: 'NVIDIA',
    features: ['24GB GDDR6X', 'Ray Tracing', 'DLSS 3.0'],
    specifications: {
      'Memória': '24GB GDDR6X',
      'Clock Boost': '2520 MHz',
      'Largura de Banda': '1008 GB/s',
    },
  },
  {
    id: '5',
    name: 'Intel i9 13900K',
    category: 'Processadores',
    price: 3499.99,
    originalPrice: 3999.99,
    image: `${baseImageUrl}?text=i9+13900K`,
    rating: 4.8,
    description: 'Processador de 24 núcleos e 32 threads para desempenho extremo.',
    inStock: true,
    brand: 'Intel',
    features: ['24 núcleos', '32 threads', 'Até 5.8GHz'],
    specifications: {
      'Núcleos': '24 (8P + 16E)',
      'Threads': '32',
      'Frequência Base': '3.0 GHz',
      'Frequência Turbo': '5.8 GHz',
    },
  },
  {
    id: '6',
    name: 'Monitor Gamer 240Hz',
    category: 'Monitores',
    price: 2899.99,
    originalPrice: 3299.99,
    image: `${baseImageUrl}?text=Monitor+240Hz`,
    rating: 4.7,
    description: 'Monitor de 27 polegadas com taxa de atualização de 240Hz para jogos competitivos.',
    inStock: true,
    brand: 'ASUS',
    features: ["27' QHD", '240Hz', '1ms', 'G-SYNC'],
    specifications: {
      'Tamanho': '27 polegadas',
      'Resolução': '2560x1440 (QHD)',
      'Taxa de Atualização': '240Hz',
      'Tempo de Resposta': '1ms',
    },
  },
  {
    id: '7',
    name: 'Teclado Mecânico RGB',
    category: 'Periféricos',
    price: 799.99,
    originalPrice: 899.99,
    image: `${baseImageUrl}?text=Teclado+Mecanico`,
    rating: 4.5,
    description: 'Teclado mecânico com switches azuis e iluminação RGB personalizável.',
    inStock: true,
    brand: 'Redragon',
    features: ['Switches Azuis', 'RGB Ajustável', 'Repouso de Pulso'],
    specifications: {
      'Tipo de Switch': 'Blue',
      'Retroiluminação': 'RGB',
      'Teclas': '104',
      'Conexão': 'USB',
    },
  },
  {
    id: '8',
    name: 'Mouse Gamer Sem Fio',
    category: 'Periféricos',
    price: 499.99,
    originalPrice: 599.99,
    image: `${baseImageUrl}?text=Mouse+Gamer`,
    rating: 4.6,
    description: 'Mouse gamer sem fio com sensor óptico de 16000 DPI.',
    inStock: true,
    brand: 'Logitech',
    features: ['16000 DPI', 'Sem Fio', 'RGB'],
    specifications: {
      'DPI Máximo': '16000',
      'Taxa de Sondagem': '1000Hz',
      'Botões Programáveis': '8',
      'Peso': '80g',
    },
  },
];
